const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("higherkey", {
  getSettings: () => ipcRenderer.invoke("settings:get"),
  setSettings: (settings) => ipcRenderer.invoke("settings:set", settings),
  pickDirectory: (kind) => ipcRenderer.invoke("dialog:pickDirectory", kind),
  useCurrentRepoProject: () => ipcRenderer.invoke("project:useCurrentRepo"),
  startWatcher: () => ipcRenderer.invoke("pipeline:startWatcher"),
  stopWatcher: () => ipcRenderer.invoke("pipeline:stopWatcher"),
  runPipelineOnce: () => ipcRenderer.invoke("pipeline:runOnce"),
  runFullMediaPrep: () => ipcRenderer.invoke("pipeline:runFullMediaPrep"),
  runOrchestratorOnce: () => ipcRenderer.invoke("orchestrator:runOnce"),
  buildMediaCache: () => ipcRenderer.invoke("media:buildCache"),
  archiveTestMedia: () => ipcRenderer.invoke("media:archiveTestMedia"),
  repairProjectMedia: () => ipcRenderer.invoke("media:repairProject"),
  runColorSchool: () => ipcRenderer.invoke("school:runColor"),
  runAudioSchool: () => ipcRenderer.invoke("school:runAudio"),
  exportSocialPacks: (options) => ipcRenderer.invoke("social:exportPacks", options),
  runDiagnostics: () => ipcRenderer.invoke("diagnostics:run"),
  runMaintenance: () => ipcRenderer.invoke("runtime:runMaintenance"),
  buildRuntimeSnapshot: () => ipcRenderer.invoke("runtime:buildSnapshot"),
  getClientState: () => ipcRenderer.invoke("runtime:getClientState"),
  buildClientWorkflow: () => ipcRenderer.invoke("workflow:buildClient"),
  getClientWorkflow: () => ipcRenderer.invoke("workflow:getClient"),
  createDemoProject: () => ipcRenderer.invoke("workflow:createDemoProject"),
  collectClientFeedback: (options) => ipcRenderer.invoke("feedback:collectClient", options),
  createIssueReport: () => ipcRenderer.invoke("support:createIssueReport"),
  openIssueReportFolder: () => ipcRenderer.invoke("support:openIssueReportFolder"),
  buildTrialPackage: () => ipcRenderer.invoke("trial:buildPackage"),
  openTrialPackageFolder: () => ipcRenderer.invoke("trial:openPackageFolder"),
  getTrialReadiness: () => ipcRenderer.invoke("trial:getReadiness"),
  getStorageReport: () => ipcRenderer.invoke("storage:getReport"),
  getClientStorage: () => ipcRenderer.invoke("storage:getClient"),
  buildCleanupPlan: (options) => ipcRenderer.invoke("storage:buildCleanupPlan", options),
  applyCleanupPlan: (options) => ipcRenderer.invoke("storage:applyCleanupPlan", options),
  archiveGeneratedArtifacts: (options) => ipcRenderer.invoke("storage:archiveGeneratedArtifacts", options),
  vacuumRuntimeDb: (options) => ipcRenderer.invoke("storage:vacuumRuntimeDb", options),
  checkUpgradeStatus: () => ipcRenderer.invoke("upgrade:getStatus"),
  buildUpgradePlan: () => ipcRenderer.invoke("upgrade:buildPlan"),
  runUpgradeCheck: () => ipcRenderer.invoke("upgrade:runCheck"),
  runLaunchPreflight: () => ipcRenderer.invoke("upgrade:launchPreflight"),
  validateDataContract: () => ipcRenderer.invoke("upgrade:validateDataContract"),
  enqueueFullMediaPrep: () => ipcRenderer.invoke("tasks:enqueueFullMediaPrep"),
  getTaskSummary: () => ipcRenderer.invoke("tasks:getSummary"),
  runTaskWorkerOnce: () => ipcRenderer.invoke("tasks:runWorkerOnce"),
  startWorker: () => ipcRenderer.invoke("worker:start"),
  stopWorker: () => ipcRenderer.invoke("worker:stop"),
  restartWorker: () => ipcRenderer.invoke("worker:restart"),
  getWorkerStatus: () => ipcRenderer.invoke("worker:status"),
  runWorkerOnce: () => ipcRenderer.invoke("worker:once"),
  pauseWorker: () => ipcRenderer.invoke("worker:pause"),
  resumeWorker: () => ipcRenderer.invoke("worker:resume"),
  startLocalApi: () => ipcRenderer.invoke("localApi:start"),
  stopLocalApi: () => ipcRenderer.invoke("localApi:stop"),
  getLocalApiStatus: () => ipcRenderer.invoke("localApi:status"),
  callLocalApi: (path, options) => ipcRenderer.invoke("localApi:call", path, options),
  getRuntimeMetrics: () => ipcRenderer.invoke("observability:getRuntimeMetrics"),
  getClientMetrics: () => ipcRenderer.invoke("observability:getClientMetrics"),
  getAuditLog: () => ipcRenderer.invoke("observability:getAuditLog"),
  buildObservabilityReport: () => ipcRenderer.invoke("observability:buildReport"),
  getSecurityStatus: () => ipcRenderer.invoke("security:getStatus"),
  runSecurityCheck: () => ipcRenderer.invoke("security:runCheck"),
  runStateReconciliation: (options) => ipcRenderer.invoke("state:reconcile", options),
  getClientIntegrity: () => ipcRenderer.invoke("state:getClientIntegrity"),
  getReconciliationReport: () => ipcRenderer.invoke("state:getReconciliationReport"),
  backupProject: (options) => ipcRenderer.invoke("project:backup", options),
  validateProject: () => ipcRenderer.invoke("project:validate"),
  buildProjectSizeReport: () => ipcRenderer.invoke("project:sizeReport"),
  resetDemoWorkspace: (options) => ipcRenderer.invoke("project:resetDemo", options),
  archiveProjectArtifacts: (options) => ipcRenderer.invoke("project:archiveArtifacts", options),
  runFullQa: () => ipcRenderer.invoke("qa:runFull"),
  getAppInfo: () => ipcRenderer.invoke("app:info"),
  showAbout: () => ipcRenderer.invoke("app:about"),
  runFirstRunSetup: () => ipcRenderer.invoke("setup:firstRun"),
  openContentInbox: () => ipcRenderer.invoke("folder:openContentInbox"),
  openSocialExports: () => ipcRenderer.invoke("folder:openSocialExports"),
  pipelineStatus: () => ipcRenderer.invoke("pipeline:status"),
  importFootage: () => ipcRenderer.invoke("files:importFootage"),
  importAndProcessFootage: () => ipcRenderer.invoke("files:importAndProcessFootage"),
  importAndQueueFootage: () => ipcRenderer.invoke("files:importAndQueueFootage"),
  verifyImportBridge: () => ipcRenderer.invoke("files:verifyImportBridge"),
  verifyImportAndProcessBridge: () => ipcRenderer.invoke("files:verifyImportAndProcessBridge"),
  getDroppedFilePaths: (files) => Array.from(files || []).map((file) => ({
    name: file.name || "",
    path: webUtils.getPathForFile(file) || file.path || "",
    size: file.size || 0,
    type: file.type || ""
  })),
  ingestDroppedFiles: (paths) => ipcRenderer.invoke("files:ingestDropped", paths),
  testNotification: () => ipcRenderer.invoke("notify:test"),
  onSettingsChanged: (callback) => ipcRenderer.on("higherkey:settings", (_event, settings) => callback(settings)),
  onProjectChanged: (callback) => ipcRenderer.on("higherkey:project", (_event, info) => callback(info))
});
